/* eslint-disable @typescript-eslint/no-var-requires */
/**
 * app.config.js
 *
 * Dynamic Expo config – reads values from .env at build time.
 * Expo automatically loads .env files before evaluating this file.
 *
 * @see https://docs.expo.dev/guides/environment-variables/
 */

module.exports = {
  expo: {
    name: 'Poolora',
    slug: 'poolora',
    version: '1.0.0',
    icon: './assets/icon.png',
    // Report the phone's light/dark setting to the app (Expo defaults to light).
    userInterfaceStyle: 'automatic',
    orientation: 'portrait',
    android: {
      package: 'com.poolora.app',
      adaptiveIcon: {
        foregroundImage: './assets/adaptive-icon.png',
        backgroundImage: './assets/adaptive-icon-background.png',
        backgroundColor: '#0B7A75',
      },
      googleServicesFile: './google-services.json',
      permissions: ['ACCESS_FINE_LOCATION', 'ACCESS_COARSE_LOCATION'],
    },
    autolinking: {
      searchPaths: ['./node_modules'],
    },
    ios: {
      bundleIdentifier: 'com.poolora.app',
      infoPlist: {
        NSLocationWhenInUseUsageDescription:
          'Poolora needs your location to show your position on the map and find rides near you.',
      },
    },
    plugins: [
      '@react-native-firebase/app',
      '@react-native-firebase/auth',
      '@react-native-community/datetimepicker',
      '@sentry/react-native',
      [
        'expo-splash-screen',
        {
          image: './assets/splash-icon.png',
          imageWidth: 220,
          resizeMode: 'contain',
          // Matches the in-app splash screen (theme primary) for a seamless handoff
          backgroundColor: '#0B7A75',
        },
      ],
      'expo-status-bar',
      [
        'expo-location',
        {
          locationWhenInUsePermission:
            'Poolora needs your location to show your position on the map and find rides near you.',
        },
      ],
      [
        'expo-image-picker',
        {
          photosPermission: 'Poolora uses your photos so you can add driver verification documents and a profile picture.',
          cameraPermission: 'Poolora uses the camera so you can photograph driver verification documents.',
        },
      ],
      // Maps: MapLibre with free OpenStreetMap tiles, no API key
      '@maplibre/maplibre-react-native',
      '@react-native-google-signin/google-signin',
      'expo-font',
      'expo-secure-store',
      '@sentry/react-native/expo',
    ],
    // Disable Over-the-Air updates in native builds to avoid remote update downloads
    // Rebuild the native app for this change to take effect.
    updates: {
      enabled: false,
      checkAutomatically: 'ON_ERROR_RECOVERY',
      // runtimeVersion can be added if using EAS updates
      // runtimeVersion: { policy: 'appVersion' },
    },
    extra: {
      // Maps need no key. MAPS_ENABLED=false shows placeholders instead, and
      // MAP_STYLE_LIGHT / MAP_STYLE_DARK swap in another MapLibre style URL.
      mapsEnabled: process.env.MAPS_ENABLED !== 'false',
      mapStyleLight: process.env.MAP_STYLE_LIGHT ?? '',
      mapStyleDark: process.env.MAP_STYLE_DARK ?? '',
      // @nathi_mike/poolora on expo.dev. Not a secret; EAS_PROJECT_ID overrides it.
      eas: {
        projectId: process.env.EAS_PROJECT_ID || '1867e068-e5c9-4468-949a-efb9c5cb5a34',
      },
    },
    owner: 'nathi_mike',
    splash: {
      // Generated by scripts/generate_brand_assets.py
      image: './assets/splash-icon.png',
      resizeMode: 'contain',
      backgroundColor: '#0B7A75',
    },
  },
};
