global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'poolora-backend'
    metrics_path: /metrics
    static_configs:
      - targets: ['app:5002']
        labels:
          service: backend

  - job_name: 'poolora-ml'
    metrics_path: /metrics
    static_configs:
      - targets: ['ml-engine:8000']
        labels:
          service: ml-engine

  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
