apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: shared-storage
  namespace: sanchari
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Gi
  storageClassName: standard