apiVersion: v1
kind: ResourceQuota
metadata:
  name: sanchari-quota
  namespace: sanchari
spec:
  hard:
    requests.cpu: "4"
    requests.memory: 8Gi
    limits.cpu: "8"
    limits.memory: 16Gi
    persistentvolumeclaims: "10"
    pods: "50"
    services: "20"
    secrets: "10"
    configmaps: "10"